on: [push, pull_request]
name: release
jobs:
  verify:
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: faq-bot-user
          POSTGRES_DB: faq-bot-db-test
          POSTGRES_PASSWORD: faq-bot-pass
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        ruby-version: [2.5]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: Setup database test
        run: |
          cp config/application.yml.sample config/application.yml
          bundle exec rails db:create db:migrate
      - name: Test using rspec
        run: |
          bundle exec rspec -fd
  deploy:
    needs: verify
    strategy:
      matrix:
        ruby-version: [2.5]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Deploy to Heroku
        run: |
          gem install dpl
          dpl --provider=heroku --app=${{ secrets.HEROKU_PRODUCTION_APP }} --api-key=${{ secrets.HEROKU_API_KEY }}
